"""ComfyUI TwitterChat - 美女人设推文生成系统"""
import os
import sys

# 首先添加当前目录到 Python 路径（让 utils 和 tools 可以被导入）
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

# 现在可以安全地导入节点
from .nodes.persona_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY
from .nodes.context_gatherer import NODE_CLASS_MAPPINGS as CONTEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONTEXT_DISPLAY
from .nodes.image_prompt_builder import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY
from .nodes.tweet_generator import NODE_CLASS_MAPPINGS as TWEET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TWEET_DISPLAY
from .nodes.calendar_manager import NODE_CLASS_MAPPINGS as CALENDAR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CALENDAR_DISPLAY
from .nodes.lora_loader import NODE_CLASS_MAPPINGS as LORA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_DISPLAY
from .nodes.output_manager import NODE_CLASS_MAPPINGS as OUTPUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_DISPLAY

# 合并所有节点
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CONTEXT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TWEET_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CALENDAR_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LORA_MAPPINGS)
NODE_CLASS_MAPPINGS.update(OUTPUT_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CONTEXT_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(TWEET_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CALENDAR_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(LORA_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(OUTPUT_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
